---
- hosts: genkifitness_backend
  pre_tasks:
      - name: update apt cache if needed.
        become: yes
        become_method: sudo
        apt: update_cache=yes cache_valid_time=3600
  tasks:
      - name: 安装用于管理apt源工具
        become: yes
        become_method: sudo
        apt: name={{item}} state=present
        with_items:
            - python-apt
            - python-pycurl
            - python-mysqldb
      - name: 添加php的ondrej源
        become: yes
        become_method: sudo
        apt_repository: repo='ppa:ondrej/php' update_cache=yes
      - name: 安装 nginx,memcached,php 以及拓展依赖
        become: yes
        become_method: sudo
        apt: name={{ item }} state=present
        with_items:
             -  git
             -  curl
             -  memcached
             -  php5.6
             -  php-cli
             -  php-common
             -  php-gd
             -  php-gettext
             -  php-igbinary
             -  php-memcache
             -  php-memcached
             -  php-msgpack
             -  php-pear
             -  php-snmp
             -  php-xdebug
             -  php5.6
             -  php5.6-cli
             -  php5.6-common
             -  php5.6-curl
             -  php5.6-fpm
             -  php5.6-gd
             -  php5.6-json
             -  php5.6-mbstring
             -  php5.6-mcrypt
             -  php5.6-mysql
             -  php5.6-opcache
             -  php5.6-readline
             -  php5.6-soap
             -  php5.6-xml
             -  postfix
             -  mysql-server
             -  mysql-client
      - name: "stop ufw"
        become: yes
        become_method: sudo
        service: name=ufw state=stopped
      - name: backup oldnginxconfig
        become: yes
        become_method: sudo
        shell: >
           mv /etc/nginx /etc/nginx.bak
      - name: backup oldphpconfig
        become: yes
        become_method: sudo
        shell: >
           mv /etc/php/5.6 /etc/php/5.6.bak
      - name: backup oldmemcacheconfig
        become: yes
        become_method: sudo
        shell: >
           mv /etc/memcached.conf /etc/memcached.conf.bak
      - name: backup oldphpconfig
        become: yes
        become_method: sudo
        shell: >
           mv /etc/mysql /etc/mysql.bak
      - name: Extract nginxconfig into dir
        become: yes
        become_method: sudo
        unarchive:
           src: "https://admin.genkifitness.com/geadm/nginxgenadmin.tar.gz"
           dest: "/etc/"
           remote_src: yes
      - name: Extract phpconfig into dir
        become: yes
        become_method: sudo
        unarchive:
           src: "https://admin.genkifitness.com/geadm/5.6genadminphp.tar.gz"
           dest: "/etc/php"
           remote_src: yes
      - name: Extract sslconfig into dir
        become: yes
        become_method: sudo
        unarchive:
           src: "https://admin.genkifitness.com/geadm/bestdealsgenad.tar.gz"
           dest: "/etc/ssl"
           remote_src: yes
      - name: Extract mysqlconfig into dir
        become: yes
        become_method: sudo
        unarchive:
           src: "https://admin.genkifitness.com/geadm/mysqlgead.tar.gz"
           dest: "/etc/"
           remote_src: yes
      - name: Extract appsrc into dir
        become: yes
        become_method: sudo
        unarchive:
           src: "https://admin.genkifitness.com/geadm/crazysalgenadm.tar.gz"
           dest: "/home"
           group: crazysal
           owner: crazysal
           remote_src: yes
      - name: Extract postfixconfig into dir
        become: yes
        become_method: sudo
        unarchive:
           src: "https://admin.genkifitness.com/geadm/postfixfront.tar.gz"
           dest: "/etc/"
           remote_src: yes
      - name: configure postfix CAfile
        become: yes
        become_method: sudo
        shell: >
           postconf -e 'smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt'
      - name: get memchachconfig into dir
        become: yes
        become_method: sudo
        get_url:
           url: "https://admin.genkifitness.com/geadm/memcached.conf"
           dest: "/etc/"
           mode: 0644
      - name: start memcache,nginx,php
        become: yes
        become_method: sudo
        service: "name={{ item }} state=started enabled=yes"
        with_items:
             - nginx
             - php5.6-fpm
             - memcached
             - postfix
             - mysql
      - name: create databases genkifitness
        mysql_db:
            login_host: "127.0.0.1"
            login_user: "root"
            login_port: "3306"
            name: ""genkifitness
            encoding: "utf8"
            state: "present"
      - name: create databases  genkifitness user
        mysql_user:
            login_host: "127.0.0.1"
            login_user: "root"
            login_port: "3306"
            name: "genkifitness"
            password: "nohack"
            host: "172.30.0.%"
            priv: 'genkifitness.*:ALL'
            state: "present"
