---
- hosts: genkifitness_backend
  pre_tasks:
      - name: update apt cache if needed.
        become: yes
        become_method: sudo
        apt: update_cache=yes cache_valid_time=3600
  tasks:
      - name: 安装用于管理apt源工具
        become: yes
        become_method: sudo
        apt: name={{item}} state=present
        with_items:
            - python-apt
            - python-pycurl
            - python-mysqldb
      - name: 添加php的ondrej源
        become: yes
        become_method: sudo
        apt_repository: repo='ppa:ondrej/php' update_cache=yes
      - name: 安装 nginx,memcached,php 以及拓展依赖
        become: yes
        become_method: sudo
        apt: name={{ item }} state=present
        with_items:
             -  git
             -  curl
             - dh-php
               php-cli-prompt
               php-common
               php-composer-semver
               php-composer-spdx-licenses
               php-igbinary
               php-imagick
               php-json-schema
               php-memcache
               php-memcached
               php-msgpack
               php-pear
               php-symfony-console
               php-symfony-filesystem
               php-symfony-finder
               php-symfony-process
               php5.6-cli
               php5.6-common
               php5.6-curl
               php5.6-dev
               php5.6-fpm
               php5.6-gd
               php5.6-imap
               php5.6-intl
               php5.6-json
               php5.6-mbstring
               php5.6-mcrypt
               php5.6-mysql
               php5.6-opcache
               php5.6-pspell
               php5.6-readline
               php5.6-recode
               php5.6-snmp
               php5.6-sqlite3
               php5.6-tidy
               php5.6-xml
               php5.6-xmlrpc
               php5.6-xsl
               php5.6-zip
               pkg-php-tools
               memcached
               postfix
               mysql-server
               mysql-client

             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
             -
      - name: "stop ufw"
        become: yes
        become_method: sudo
        service: name=ufw state=stopped
      - name: backup oldnginxconfig
        become: yes
        become_method: sudo
        shell: >
           mv /etc/nginx /etc/nginx.bak
      - name: backup oldphpconfig
        become: yes
        become_method: sudo
        shell: >
           mv /etc/php/7.0 /etc/php/7.0.bak
      - name: backup oldmemcacheconfig
        become: yes
        become_method: sudo
        shell: >
           mv /etc/memcached.conf /etc/memcached.conf.bak

      - name: Extract nginxconfig into dir
        become: yes
        become_method: sudo
        unarchive:
           src: "https://www.genkifitness.com/ge/nginxgenkifitness.tar.gz"
           dest: "/etc/"
           remote_src: yes
      - name: Extract phpconfig into dir
        become: yes
        become_method: sudo
        unarchive:
           src: "https://www.genkifitness.com/ge/7.0genki.tar.gz"
           dest: "/etc/php"
           remote_src: yes
      - name: Extract sslconfig into dir
        become: yes
        become_method: sudo
        unarchive:
           src: "https://www.genkifitness.com/ge/genkifitness.tar.gz"
           dest: "/etc/ssl"
           remote_src: yes
      - name: Extract appsrc into dir
        become: yes
        become_method: sudo
        unarchive:
           src: "https://www.genkifitness.com/ge/crazysal.tar.gz"
           dest: "/home"
           group: crazysal
           owner: crazysal
           remote_src: yes
      - name: get memchachconfig into dir
        become: yes
        become_method: sudo
        get_url:
           url: "https://www.genkifitness.com/ge/memcached.conf"
           dest: "/etc/"
           mode: 0644
      - name: start memcache,nginx,php
        become: yes
        become_method: sudo
        service: "name={{ item }} state=started enabled=yes"
        with_items:
             - nginx
             - php7.0-fpm
             - memcached